# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

fastlane_require 'dotenv'

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Firebase App Distribution"
  lane :betadeploy do
    release_notes = prompt(text: "Release Note: ")
    releaseFilePath = File.join(Dir.pwd, "../..", "upload-keystore.jks")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "yj-admin-upload",
        "android.injected.signing.key.password" => ENV["KEYSTORE_PASSWORD"],
      }
    )
    release = firebase_app_distribution(
      app: "1:329840334591:android:62e5425613951fe9b61eca",
      firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
      testers: "gohjx8808@gmail.com",
      release_notes:release_notes
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
